// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace KhulnasoftVS
{
    internal sealed partial class Vsix
    {
        public const string Id = "Khulnasoft.VisualStudio";
        public const string Name = "Khulnasoft";
        public const string Description = @"The modern coding superpower: free AI code acceleration plugin for your favorite languages. Type less. Code more. Ship faster.";
        public const string Language = "en-US";
        public const string Version = "1.8.82";
        public const string Author = "Khulnasoft";
        public const string Tags = "";
    }
}
